server:
  port: 18866
  undertow:
    io-threads: 16
    worker-threads: 256
    buffer-size: 1024
    direct-buffers: true
    
    
spring:
  datasource:
    hikari:
      connection-test-query: SELECT 1
      minimum-idle: 5
      maximum-pool-size: 50
      pool-name: terminalpool
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/netty-mqtt?autoReconnect=true&useSSL=false&?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
    username: ${AUTH_DB_PWD:root}
    password: ${AUTH_DB_USER:root}
    type: com.zaxxer.hikari.HikariDataSource
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true  
    
  redis:
    database: 15
    timeout: 0
    host: 127.0.0.1
    port: 6379
    password: pass
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 8
      min-idle: 0   
    
netty:
  port: 6666    
    

          
    
        